name = "r2-explorer-e2e"
compatibility_date = "2024-11-06"
main = "e2e.ts"
workers_dev = true
assets = { directory = "../../dashboard/dist/spa", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application", run_worker_first = ["/api/*", "/share/*"] }

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'my-bucket'
